run-dev:
	# cp dev.env .env
	poetry run python src/main.py

# build:
# 	docker build -t trade-to-ohlc.

# run:
# 	docker run \
# 	 --network=redpanda_network \
# 	 --env-file prod.env \
# 	 trade-to-ohlc
